In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Predict Credit Card Fraud

In [5]:
# Load the data
transactions = pd.read_csv('transactions.csv')

In [8]:
transactions.head()

step      type     amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     8  CASH_OUT  158007.12   C424875646           0.00            0.00   
1   236  CASH_OUT  457948.30  C1342616552           0.00            0.00   
2    37   CASH_IN  153602.99   C900876541    11160428.67     11314031.67   
3   331  CASH_OUT   49555.14   C177696810       10865.00            0.00   
4   250  CASH_OUT   29648.02   C788941490           0.00            0.00   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  
0  C1298177219       474016.32      1618631.97        0  
1  C1323169990      2720411.37      3178359.67        0  
2   C608741097      3274930.56      3121327.56        0  
3   C462716348            0.00        49555.14        0  
4  C1971700992        56933.09        86581.10        0

In [9]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199999 entries, 0 to 199998
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   step            199999 non-null  int64  
 1   type            199999 non-null  object 
 2   amount          199999 non-null  float64
 3   nameOrig        199999 non-null  object 
 4   oldbalanceOrg   199999 non-null  float64
 5   newbalanceOrig  199999 non-null  float64
 6   nameDest        199999 non-null  object 
 7   oldbalanceDest  199999 non-null  float64
 8   newbalanceDest  199999 non-null  float64
 9   isFraud         199999 non-null  int64  
dtypes: float64(5), int64(2), object(3)
memory usage: 15.3+ MB


In [10]:
# How many fraudulent transactions?
transactions.isFraud.sum()

np.int64(282)

#### clean data

In [11]:
# Summary statistics on amount column
transactions.amount.describe()

count    1.999990e+05
mean     1.802425e+05
std      6.255482e+05
min      0.000000e+00
25%      1.338746e+04
50%      7.426695e+04
75%      2.086376e+05
max      5.204280e+07
Name: amount, dtype: float64

In [12]:
# Create isPayment field
transactions['isPayment'] = transactions.type.isin(['PAYMENT', 'DEBIT']).astype(int)

In [14]:
# Create isMovement field
transactions['isMovement'] = transactions.type.isin(['CASH_OUT', 'TRANSFER']).astype(int)

In [15]:
# Create accountDiff field
transactions['accountDiff'] = np.abs(transactions.oldbalanceOrg - transactions.oldbalanceDest)

In [17]:
# Create features and label variables
features = transactions[['amount', 'isPayment', 'isMovement', 'accountDiff']]
label = transactions.isFraud

In [20]:
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.3)

In [19]:
# Normalize the features variables
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#### model

In [21]:
# Fit the model to the training data
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [22]:
# Score the model on the training data
lr.score(X_train, y_train)

0.9985785612754376

In [23]:
# Score the model on the test data
lr.score(X_test, y_test)

0.9985333333333334

In [24]:
# Print the model coefficients
lr.coef_

array([[ 4.63280321e-07, -5.06055150e+00, -4.37605283e-01,
        -2.27923552e-07]])

#### predict

In [25]:
# New transaction data
transaction1 = np.array([123456.78, 0.0, 1.0, 54670.1])
transaction2 = np.array([98765.43, 1.0, 0.0, 8524.75])
transaction3 = np.array([543678.31, 1.0, 0.0, 510025.5])

# Combine new transactions into a single array
sample_transactions = np.stack((transaction1, transaction2, transaction3))

In [26]:
# Normalize the new transactions
sample_transactions = scaler.transform(sample_transactions)

/home/xy/.local/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [27]:
# Predict fraud on the new transactions
lr.predict(sample_transactions)

/home/xy/.local/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0, 0, 0])

In [28]:
# Show probabilities on the new transactions
lr.predict_proba(sample_transactions)

/home/xy/.local/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[9.25655884e-01, 7.43441163e-02],
       [9.99995395e-01, 4.60464063e-06],
       [9.99995395e-01, 4.60464205e-06]])