## Classifying Tweets

use a Naive Bayes Classifier to find patterns in real tweets. We've got three files: `new_york.json`, `london.json`, and `paris.json`, which contain tweets gathered from those locations.

The goal is to create a classification algorithm that can classify any tweet (or sentence) and predict whether that sentence came from New York, London or Paris.

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [15]:
import matplotlib.pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
from sklearn.preprocessing import scale

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

### Investigate the Data

In [1]:
new_york_tweets = pd.read_json("new_york.json", lines=True)

In [2]:
print(len(new_york_tweets))
print(new_york_tweets.columns)
print(new_york_tweets.loc[12]["text"])

4723
Index(['created_at', 'id', 'id_str', 'text', 'display_text_range', 'source',
       'truncated', 'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str',
       'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place',
       'contributors', 'is_quote_status', 'quote_count', 'reply_count',
       'retweet_count', 'favorite_count', 'entities', 'favorited', 'retweeted',
       'filter_level', 'lang', 'timestamp_ms', 'extended_tweet',
       'possibly_sensitive', 'quoted_status_id', 'quoted_status_id_str',
       'quoted_status', 'quoted_status_permalink', 'extended_entities',
       'withheld_in_countries'],
      dtype='object')
Be best #ThursdayThoughts


How many London tweets are there? How many Paris ones are there?

In [3]:
london_tweets = pd.read_json("london.json", lines=True)
print(len(london_tweets))

5341


In [4]:
paris_tweets = pd.read_json("paris.json", lines=True)
print(len(paris_tweets))

2510


### Classifying using language: Naive Bayes Classifier

begin by looking at the way language is used differently in these three locations. Let's grab the text of all of the tweets and make it one big list. Then combine all three into a variable.

Make the labels associated with those tweets. `0` represents a New York tweet, `1`  represents a London tweet, and `2` represents a Paris tweet.

In [5]:
new_york_text = new_york_tweets["text"].tolist()
london_text = london_tweets["text"].tolist()
paris_text = paris_tweets["text"].tolist()

all_tweets = new_york_text + london_text + paris_text
labels = [0] * len(new_york_text) + [1] * len(london_text) + [2] * len(paris_text)

### Making a Training and Test Set

In [6]:
train_data, test_data, train_labels, test_labels = train_test_split(all_tweets, labels, 
                                                                    test_size=0.2, random_state=1)
print(len(train_data), len(test_data))

10059 2515


### Making the Count Vectors

To use a Naive Bayes Classifier, we need to transform our lists of words into count vectors.

In [7]:
counter = CountVectorizer()

In [8]:
counter.fit(train_data)

,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(1, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [9]:
train_counts = counter.transform(train_data)
test_counts = counter.transform(test_data)

In [10]:
print(train_data[3])

saying bye is hard. Especially when youre saying bye to comfort.


In [11]:
print(test_data[3])

Trade &amp; investment agreements often have a negative effect on the weakest parts of society, in particular women. Ho… https://t.co/Ve3JlBzNlZ


### Train and Test the Naive Bayes Classifier

use the CountVectors to train and test the Naive Bayes Classifier.

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [12]:
classifier = MultinomialNB()
classifier.fit(train_counts, train_labels)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [13]:
predictions = classifier.predict(test_counts)

### Evaluating the Model

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [14]:
accuracy_score(test_labels, predictions)

0.6779324055666004

There were three classes &mdash; `0` for New York, `1` for London, and `2` for Paris.

In [15]:
confusion_matrix(test_labels, predictions)

array([[541, 404,  28],
       [203, 824,  34],
       [ 38, 103, 340]])

### Test Your Own Tweet

The confusion matrix should line up with intuition. The classifier predicts tweets that were actually from New York as either New York tweets or London tweets, but almost never Paris tweets. Similarly, the classifier rarely misclassifies the tweets that were actually from Paris. Tweets coming from two English speaking countries are harder to distinguish than tweets in different languages.

Now write a tweet and see how the classifier works. Remember a `0` represents New York, a `1` represents London, and a `2` represents Paris.

In [16]:
tweet = "I'll soon win the game!!"
tweet_counts = counter.transform([tweet])
classifier.predict(tweet_counts)

array([1])

In [17]:
tweet = "We need a better president."
tweet_counts = counter.transform([tweet])
classifier.predict(tweet_counts)

array([0])

In [18]:
tweet = "On n'a pas des ressources."
tweet_counts = counter.transform([tweet])
classifier.predict(tweet_counts)

array([2])

## Viral Tweets

use the K-Nearest Neighbor algorithm to predict whether a tweet will go viral.

Which features of a tweet are most closely linked to its popularity? Maybe the number of hashtags or the number of links in the tweet strongly influences its popularity. Maybe its virality is dependent on how many followers the person has. Maybe it's something more subtle like the specific language used in the tweets.

The feature `"user"` is a dictionary. We might want to use some of the information found in these sub-dictionaries.

In [1]:
all_tweets = pd.read_json("random_tweets.json", lines=True)

print(len(all_tweets))
print(all_tweets.columns)
print(all_tweets.loc[0]['text'])

#Print the user here and the user's location here.
print(all_tweets.loc[0]['user'])
print(all_tweets.loc[0]['user']['location'])

### Defining Viral Tweets

A K-Nearest Neighbor classifier is a supervised machine learning algorithm, and as a result, we need to have a dataset with tagged labels. For this specific example, we need a dataset where every tweet is marked as viral or not viral.

How do we define a viral tweet? A good place to start is to look at the number of retweets the tweet has. This can be found using the feature `"retweet_count"`. Let's create a column called `is_viral` that is a `1` if the tweet had more than certain threshold of retweets and `0` otherwise. Let's use the median number of retweets.

After finishing this project, come back and play with this threshold number. How would the model work if it was trying to find incredibly viral tweets? For example, how would it work if it were looking for tweets with 1000 or more retweets?

In [2]:
md = np.median(all_tweets["retweet_count"])
print(md)

In [3]:
all_tweets['is_viral'] = np.where(all_tweets['retweet_count'] > md, 1, 0)

In [5]:
all_tweets.is_viral.value_counts()

### Making Features

Which features might determine whether a tweet is viral: We can create new columns in our dataset to represent these features. For example, let's say the length of a tweet might be a valuable feature.

Here are some potential ideas for more features.

* The number of hashtags in the tweet. Fnd this by looking at the `text` of the tweet and using the `.count()` function with `#` as a parameter.
* The number of links in the tweet. Using a similar strategy to the one above, use `.count()` to count the number of times `http` appears in the tweet.
* The number of words in the tweet. Call `.split()` on the `text` of a tweet.
* The average length of the words in the tweet.

In [6]:
all_tweets['tweet_length'] = all_tweets.apply(lambda tweet: len(tweet['text']), axis=1)

In [7]:
all_tweets['followers_count'] = all_tweets.apply(lambda tweet: tweet['user']['followers_count'], axis=1)

In [8]:
all_tweets['friends_count'] = all_tweets.apply(lambda tweet: tweet['user']['friends_count'], axis=1)

### Normalizing The Data

Get rid of all the data that is no longer relevant.

The scale function will normalize the data so all of the features will vary within the same range.

In [9]:
labels = all_tweets.is_viral
data = all_tweets[['tweet_length', 'followers_count', 'friends_count']]

In [10]:
scaled_data = scale(data, axis=0)
print(scaled_data[0])

### Creating the Training Set and Test Set

In [11]:
train_data, test_data, train_labels, test_labels = train_test_split(data, labels, 
                                                                    test_size=0.2, random_state=1)

### Using the Classifier

In [12]:
k = 5
classifier = KNeighborsClassifier(n_neighbors=k)
classifier.fit(train_data, train_labels)

In [13]:
classifier.score(test_data, test_labels)

### Choosing K

We've tested our classifier with `k = 5`, but maybe there's a `k` that will work better. Let's test many different values for `k` and graph the results. 

In [18]:
k_list = range(1, 200)

In [19]:
scores = []
for k in k_list:
    classifier = KNeighborsClassifier(n_neighbors=k)
    classifier.fit(train_data, train_labels)
    scores.append(classifier.score(test_data, test_labels))

In [20]:
plt.plot(k_list, scores)
plt.xlabel('k')
plt.ylabel('scores')

The classifier gets better as `k` increases, but as `k` gets too high, underfitting starts to happen.

By using the features `tweet_length`, `followers_count`, and `friends_count`, we were able to get up to around 56% accuracy. That is better than random, but still not exceptional. Can we find some different features that perform better?